services:
  # https://zgadzaj.com/development/docker/docker-compose/containers/rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ddd.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports: # uses 5672 internally
      - 15673:15672

  recepcion-db:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    container_name: ddd.recepcion-db
    environment:
      SA_PASSWORD: "P@ssW0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - 1434:1433 # exposed just for debugging purposes

  recepcion-api:
    build:
      context: .
      dockerfile: ./Recepcion/Delgado.Ddd.Recepcion.Api/Dockerfile
    image: ddd.recepcion.api
    container_name: ddd.recepcion.api
    ports:
      - 5200:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - "ASPNETCORE_URLS=http://+"
    restart: on-failure
    depends_on:
      - rabbitmq
      - recepcion-db

  mailserver:
    image: jijiechen/papercut:latest
    container_name: ddd.papercut
    ports: # exposes port 25 internally
      - 37409:37408
